### ISSUE TITLE
Update to check new PyPI

### ISSUE THREAD

**Issue by brainwane** [tell-k/pypi-updates#1]
Hi! I suggest you update your call from [the old PyPI RSS feed](https://pypi.python.org/pypi?:action=rss) to [the new feed at https://pypi.org/rss/updates.xml](https://pypi.org/rss/updates.xml). Check out [the roadmap for redirecting traffic to the new PyPI](https://wiki.python.org/psf/WarehouseRoadmap), and for more on the new site's feeds, see https://warehouse.readthedocs.io/api-reference/feeds/ . You might also want to subscribe to the low-traffic [pypi-announce mailing list](https://mail.python.org/mm3/mailman3/lists/pypi-announce.python.org/).

**Comment by brainwane** [comment]
[Here's a fresh migration guide](https://warehouse.readthedocs.io/api-reference/integration-guide/#migrating-to-the-new-pypi). I also suggest that you update your code so the tweets link to pypi.org instead of pypi.python.org. Shorter, too!

**Comment by tell-k** [comment]
@brainwane Thank you for teaching me. I will fix it soon.

**Comment by tell-k** [comment]
fixed.
